import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/nav";
import Layout from "@/components/Layout";
import { getServerSession } from "next-auth";
import authOptions from "./api/auth/[...nextauth]/option";
import SessionAccProvider from "@/context/client-provider";
import { Toaster } from "@/components/ui/toaster";
import SignStatus from "@/components/Register/SignFlow";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log(session)
  
  return (
    <html lang="en">
      <SessionAccProvider session={session}>
        
      <body className={`${inter.className}`}>
        
        <Layout>
        <Navigation/>
        { !session ? <SignStatus  /> : children }
        </Layout>
        </body>
        <Toaster />
      </SessionAccProvider>
    </html>
  );
}
